# Generated by Django 3.1.7 on 2021-04-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('mood', models.CharField(max_length=64)),
                ('sleep', models.CharField(max_length=64)),
                ('meals', models.CharField(max_length=64)),
                ('meetings', models.CharField(max_length=64)),
                ('diary', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
