# Generated by Django 3.1.7 on 2021-04-07 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210407_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 38, 34, 763380)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meals',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meetings',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mood',
            name='sleep',
            field=models.IntegerField(),
        ),
    ]
