# Generated by Django 3.1.7 on 2021-04-08 05:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20210408_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 5, 24, 3, 924195)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moods', to='website.feeling'),
        ),
    ]
