# Generated by Django 3.1.7 on 2021-04-08 05:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20210408_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meals',
            name='meals',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 5, 29, 29, 296148)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealss', to='website.feeling'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meetings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingss', to='website.feeling'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='sleep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeps', to='website.feeling'),
        ),
    ]
