# Generated by Django 3.1.7 on 2021-04-08 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20210408_0529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 5, 34, 48, 61590)),
        ),
    ]
