# Generated by Django 3.1.7 on 2021-04-08 05:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210408_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 5, 39, 9, 601234)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mealss', to='website.meals'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meetings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingss', to='website.meetings'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='sleep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeps', to='website.sleep'),
        ),
    ]
