# Generated by Django 3.1.7 on 2021-04-08 07:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210408_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeling',
            old_name='feeling',
            new_name='feeling_options',
        ),
        migrations.RenameField(
            model_name='meals',
            old_name='meals',
            new_name='meals_options',
        ),
        migrations.RenameField(
            model_name='meetings',
            old_name='meetings',
            new_name='meetings_options',
        ),
        migrations.RenameField(
            model_name='sleep',
            old_name='sleep',
            new_name='sleep_options',
        ),
        migrations.AlterField(
            model_name='mood',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 8, 7, 43, 57, 213910)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='website.meals'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='meetings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='website.meetings'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='mood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeling', to='website.feeling'),
        ),
        migrations.AlterField(
            model_name='mood',
            name='sleep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleep', to='website.sleep'),
        ),
    ]
